# @host = 127.0.0.1:9001
# @host = api.henmao.com
@host = 182.254.138.39:9001
@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoibGl1cm9uZ3FpbmciLCJleHAiOjE2MTIxODIyODksImlhdCI6MTYxNDk0MDA5MH0.R5yQK-jrfvObrQY64wH_J6yL1WLySztWNSffeNSFwFs

## 后台相关接口
### 登录
POST /admin/login HTTP/1.1
Host: {{host}}
Cache-Control: no-Cache
content-type: application/json

{
  "username": "liurongqing",
  "password": "123456"
}

### 注册
GET /admin/register
  ?username=liurongqing
  &password=123456
Host: {{host}}
Cache-Control: no-Cache
content-type: application/json

### 获取关卡列表
GET /admin/level
Host: {{host}}
Cache-Control: no-Cache
content-type: application/json
Authorization: {{Authorization}}

### 每日重置生命
POST /admin/reset-life
Host: {{host}}
Cache-Control: no-Cache
content-type: application/json
# Authorization: {{Authorization}}

{
  "sign": "UQyvy3*rAPYt_9vXd"
}
