@host = 127.0.0.1:9001
@Authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoibGl1cm9uZ3FpbmciLCJleHAiOjE2NDkzODE0MjksImlhdCI6MTYzMTQwODQxOX0.VdX49xrSg8-fj7G3yHTZHXgMR7yMYv7jp68TS8DKTM4

## 数独库游戏相关接口

### 获取关卡列表
GET /sudoku/level HTTP/1.1
Host: {{host}}
Cache-Control: no-Cache
content-type: application/json
Authorization: {{Authorization}}


