name: 部署后台系统

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: build file
      run: yarn build --prod
    - name: deploy file to server
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./dist,./package.json
        remote_path: /home/liurongqing/api
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}
    env:
      CI: true
